version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules/
      - /app/public/qrcodes/
    env_file:
      - .env
  proxy:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/dev:/etc/nginx/conf.d
    depends_on:
      - app
