#!/usr/bin/env node
require = require('esm')(module)
const createResources = require('./create-resources')

createResources().catch(err => {
  if (err.entityType === 'entity.response') {
    console.error(JSON.stringify(err, ' ', 2))
  } else {
    console.error(err)
  }
})
