# This Serverless configuration file describes the OS Healthcare application
# server-side resources and is used by the Serverless deploy command, 'sls'
# to upload and deploy the application in your AWS account.
#
# You need to edit the environment variables below based on your Openscreen
# account information and those values should be the same as found in the
# .env file under the 'scripts/' folder.

service: healthcareapp

frameworkVersion: "2"

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  timeout: 30
  httpApi:
    cors: true
  apiGateway:
    binaryMediaTypes:
      '*.*'
  environment:
#    SEE THE EDIT-THIS!.env FILE UNDER THE scripts/ FOLDER FOR AN EXPLANATION
#    OF THESE ENVIRONMENT VARIABLES. THIS APP DOES NOT USE SERVERLESS .ENV
    OS_KEY: XXXXXXXXXXXXXXXXXX
    OS_SECRET: XXXXXXXXXXXXXXXXXXXXXXXX
    ACCOUNT_ID: AA9999AA9999AA
    PROJECT_ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    API_ENDPOINT: https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev
    OS_DEBUG: ERROR
#    DEBUG WILL CAUSE THE LAMBDAS TO DEBUG LOG THE EVENT AND RESPONSE OBJECTS
    DEBUG: YES
#    PHONE_OVERRIDE: +99999999999

functions:
  appGetPrescription:
    handler: handlers/app.getPrescriptionPage
    events:
      - http:
          path: /app/prescription
          method: get
          cors: true

  appGetPickup:
    handler: handlers/app.getPickupPage
    events:
      - http:
          path: /app/pickup
          method: get
          cors: true

  getPrescription:
    handler: handlers/prescription.getPrescription
    events:
      - http:
          path: /prescription
          method: get
          cors: true

  getPickup:
    handler: handlers/prescription.getPickup
    events:
      - http:
          path: /pickup
          method: get
          cors: true

  getPrescriptionPrepare:
    handler: handlers/prescription.getPrescriptionPrepare
    events:
      - http:
          path: /prescription/{scanId}/prepare
          method: get
          cors: true

  getPrescriptionReady:
    handler: handlers/prescription.getPrescriptionReady
    events:
      - http:
          path: /prescription/{scanId}/ready
          method: get
          cors: true

  getPrescriptionPickupQr:
    handler: handlers/prescription.getPrescriptionPickupQr
    events:
      - http:
          path: /prescription/{scanId}/pickupqr
          method: get
          cors: true

  updatePrescription:
    handler: handlers/prescription.updatePrescription
    events:
      - http:
          path: /prescription/{scanId}
          method: patch
          cors: true
