service: healthcare-app

frameworkVersion: "2"

package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ../.env

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  httpApi:
    cors: true
  environment:
    PROJECT_ID: ${env:PROJECT_ID}
    OS_KEY: ${env:OS_KEY}
    OS_SECRET: ${env:OS_SECRET}

functions:
  getPatient:
    handler: handlers/patient.getPatientByScanId
    events:
      - http:
          path: /patient/{scanId}
          method: get
          cors: true

  updatePatient:
    handler: handlers/patient.updatePatientByScanId
    events:
      - http:
          path: /patient/{scanId}
          method: patch
          cors: true

  getPharmacist:
    handler: handlers/pharmacist.getPharmacistByScanId
    events:
      - http:
          path: /pharmacist/{scanId}
          method: get
          cors: true

  updatePharmacist:
    handler: handlers/pharmacist.updatePharmacistByScanId
    events:
      - http:
          path: /pharmacist/{scanId}
          method: patch
          cors: true

