service: healthcareapp

frameworkVersion: "2"

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  timeout: 30
  httpApi:
    cors: true
  apiGateway:
    binaryMediaTypes:
      '*.*'
  environment:
    OS_KEY: XXXXXXXXXXXXXXXXXX
    OS_SECRET: XXXXXXXXXXXXXXXXXXXXXXXX
    ACCOUNT_ID: XXXXXXXXXXXXXX
    PROJECT_ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    API_ENDPOINT: https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/dev
    PHONE_OVERRIDE: +99999999999
    OS_DEBUG: ERROR
    DEBUG: YES

functions:
  appGetPrescription:
    handler: handlers/app.getPrescriptionPage
    events:
      - http:
          path: /app/prescription
          method: get
          cors: true

  appGetPickup:
    handler: handlers/app.getPickupPage
    events:
      - http:
          path: /app/pickup
          method: get
          cors: true

  getPrescription:
    handler: handlers/prescription.getPrescription
    events:
      - http:
          path: /prescription
          method: get
          cors: true

  getPickup:
    handler: handlers/prescription.getPickup
    events:
      - http:
          path: /pickup
          method: get
          cors: true

  getPrescriptionPrepare:
    handler: handlers/prescription.getPrescriptionPrepare
    events:
      - http:
          path: /prescription/{scanId}/prepare
          method: get
          cors: true

  getPrescriptionReady:
    handler: handlers/prescription.getPrescriptionReady
    events:
      - http:
          path: /prescription/{scanId}/ready
          method: get
          cors: true

  getPrescriptionPickupQr:
    handler: handlers/prescription.getPrescriptionPickupQr
    events:
      - http:
          path: /prescription/{scanId}/pickupqr
          method: get
          cors: true

  updatePrescription:
    handler: handlers/prescription.updatePrescription
    events:
      - http:
          path: /prescription/{scanId}
          method: patch
          cors: true
