module.exports = {
  QrCodeTypes: {
    PICKUP_QR: 'PICKUP_QR',
    PRESCRIPTION_QR: 'PRESCRIPTION_QR',
  },
  ContactRoles: {
    CLINIC: 'CLINIC',
    PATIENT: 'PATIENT',
    PHARMACIST: 'PHARMACIST',
  },
  PrescriptionStates: {
    PRESCRIPTION_READY: 'PRESCRIPTION_READY',
    PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
    PRESCRIPTION_PICKED_UP: 'PRESCRIPTION_PICKED_UP',
    PRESCRIPTION_ACCEPTED_BY_PATIENT: 'PRESCRIPTION_ACCEPTED_BY_PATIENT',
    PRESCRIPTION_ACCEPTED_BY_PHARMACIST: 'PRESCRIPTION_ACCEPTED_BY_PHARMACIST',
  },
  TemplateNames: {
    PRESCRIPTION_DROP_OFF: 'PRESCRIPTION_DROP_OFF',
    PRESCRIPTION_BEING_PREPARED: 'PRESCRIPTION_BEING_PREPARED',
    PRESCRIPTION_READY_FOR_PICKUP: 'PRESCRIPTION_READY_FOR_PICKUP',
  },
}
