module.exports = {

  PrescriptionStates: {
    PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
    PRESCRIPTION_ACCEPTED_BY_PATIENT: 'PRESCRIPTION_ACCEPTED_BY_PATIENT',
    PRESCRIPTION_ACCEPTED_BY_PHARMACIST: 'PRESCRIPTION_ACCEPTED_BY_PHARMACIST',
    PRESCRIPTION_READY: 'PRESCRIPTION_READY',
    PRESCRIPTION_PICKED_UP: 'PRESCRIPTION_PICKED_UP',
  }
}
