module.exports = {

  TemplateNames: {
    PRESCRIPTION_DROP_OFF: 'PRESCRIPTION_DROP_OFF',
    PRESCRIPTION_BEING_PREPARED: 'PRESCRIPTION_BEING_PREPARED',
    PRESCRIPTION_READY_FOR_PICKUP: 'PRESCRIPTION_READY_FOR_PICKUP',
  }
}
