module.export = {

  PrescriptionStates: {
    PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
    WAITING_FOR_PATIENT_CONFIRMATION_CODE: 'WAITING_FOR_PATIENT_CONFIRMATION_CODE',
    ACCEPTED_BY_PATIENT: 'ACCEPTED_BY_PATIENT',
    SENT_TO_PHARMACIST: 'SENT_TO_PHARMACIST',
    WAITING_FOR_PHARMACIST_CONFIRMATION_CODE: 'WAITING_FOR_PHARMACIST_CONFIRMATION_CODE',
    PHARMACIST_PROCESSING: 'PHARMACIST_PROCESSING',
    PRESCRIPTION_READY: 'PRESCRIPTION_READY',
  }
}
